---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.embulk.embulk-plugins"
      - dependency-name: "org.embulk:embulk-spi"
      - dependency-name: "org.embulk:embulk-util-config"
      - dependency-name: "org.embulk:embulk-util-file"
